services:
  endfield-checkin:
    build: https://github.com/endfinton/dailyendfield.git
    container_name: endfield-auto-checkin
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - /data/endfield:/app/data
    environment:
      - TZ=UTC
      - DB_PATH=/app/data/database.db
      - PORT=3001
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
networks: {}
